<?php
$translate = $this->plugin('translate');
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Source+Code+Pro|Lato:400,400italic,700,700italic');
$this->headLink()->appendStylesheet($this->assetUrl('neatline/build/'. $this->asset_manifest['main.css'], 'Neatline'));
$this->headLink()->appendStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->appendStylesheet($this->assetUrl('css/style.css', 'Omeka'));
?>

<html>
<head>
  <?php echo $this->headMeta(); ?>
  <?php echo $this->headTitle(); ?>
  <?php echo $this->headLink(); ?>
  <?php echo $this->headStyle(); ?>
  <?php echo $this->headScript(); ?>
</head>
<style>
  body {
    margin: 0 1rem;
  }
</style>
<body>
<div id="root"></div>
<script>
    window.jwt = <?php echo !$this->jwt ? 'null' : '\'' . $this->jwt . '\'' ?>;

    let baseUrl = <?php echo '\'' . $_SERVER['REQUEST_URI'] . '\'' ?>;
    baseUrl = baseUrl.replace(/(.+)\/admin\/neatline(\/.+)?/gi, '$1');

    if (baseUrl.startsWith('/admin')) {
      baseUrl = '';
    }

    window.containerFullMode = true;
    window.containerReturnBaseRoute = `${baseUrl}/admin/neatline`;
    window.baseRoute = `${baseUrl}/admin/neatline/full`;
    window.baseUrl = baseUrl;
</script>
<?php
echo $this->inlineScript()
    ->prependFile($this->assetUrl('neatline/build/' . $this->asset_manifest['main.js'], 'Neatline'));
?>
</body>
</html>
