<?php
$this->headLink()->appendStylesheet($this->assetUrl('neatline/build/'. $this->asset_manifest['main.css'], 'Neatline'));
?>
<div id="root"></div>
<script>
    window.jwt = <?php echo !$this->jwt ? 'null' : '\'' . $this->jwt . '\'' ?>;
    window.baseRoute = '/s/<?php echo $this->site_slug ?>/neatline';
</script>
<?php
echo $this->inlineScript()
    ->prependFile($this->assetUrl('neatline/build/' . $this->asset_manifest['main.js'], 'Neatline'));
?>
