<?php
$manifest = file_get_contents('modules/Neatline/asset/neatline/build/asset-manifest.json');
$asset_manifest = json_decode($manifest, true);

$this->headLink()->appendStylesheet($this->assetUrl('css/page-blocks.css', 'Omeka'));
$this->headLink()->appendStylesheet($this->assetUrl('neatline/build/'. $asset_manifest['main.css'], 'Neatline'));
$this->htmlElement('body')->appendAttribute('class', 'page');
$this->pageTitle($page->title(), 2);
$showPagePagination = $this->siteSetting('show_page_pagination', true);
?>

<script>
    let baseUrl = <?php echo '\'' . $_SERVER['REQUEST_URI'] . '\'' ?>;
    baseUrl = baseUrl.replace(/(.+)\/s\/(.+)?/gi, '$1');

    console.log(baseUrl);
    if (baseUrl.startsWith('/s')) {
      baseUrl = '';
    }

    window.baseUrl = baseUrl;
</script>

<?php
$nav = $site->publicNav();
$container = $nav->getContainer();
$activePage = $nav->findActive($container);
if ($activePage):
?>
    <?php if ($activePage['depth'] !== 0): ?>
    <nav class="breadcrumbs"><?php echo $nav->breadcrumbs(); ?></nav>
    <?php endif; ?>
<?php endif; ?>

<?php if ($activePage): ?>
    <?php if ($this->displayNavigation && $activePage['page']->hasPages()): ?>
    <nav class="sub-menu"><?php echo $nav->menu()->renderSubMenu(); ?></nav>
    <?php endif; ?>
<?php endif; ?>

<?php $this->trigger('view.show.before'); ?>
<div class="blocks">
    <?php echo $this->content; ?>
</div>
<script>
  window.baseRoute = '/s';
</script>
<?php
echo $this->inlineScript()->prependFile($this->assetUrl('neatline/build/' . $asset_manifest['main.js'], 'Neatline'));
?>
<?php $this->trigger('view.show.after'); ?>
<?php if ($showPagePagination): ?>
<?php echo $this->sitePagePagination(); ?>
<?php endif; ?>
