#!/bin/bash

# Change directory into the root directory
cd /root

# Delete the current working directory
rm -rf neatline-omeka-s/

# Clone the repository
git clone neatline-omeka-s.git neatline-omeka-s

# Change into new working directory
cd neatline-omeka-s

# Update composer
composer install