<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$label = isset($data['label']) && '' !== trim($data['label']) ? $data['label'] : null;
?>
<label><?php echo $translate('Type'); ?> <input type="text" value="<?php echo $escape($translate($link->getName())); ?>" disabled></label>
<label><?php echo $translate('Label'); ?> <input type="text" data-name="label" value="<?php echo $escape($label); ?>"></label>
